version: '3.9'

services:
  app:
    build: .
    command: pnpm dev
    working_dir: /workspace
    ports:
      - '4000:4000'
      - '5173:5173'
    volumes:
      - .:/workspace
    environment:
      PORT: 4000
